/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DiseaseInfo = IDL.Record({
  'id' : IDL.Nat,
  'plantType' : IDL.Text,
  'treatment' : IDL.Text,
  'diseaseName' : IDL.Text,
  'symptoms' : IDL.Text,
  'severity' : IDL.Text,
  'prevention' : IDL.Text,
});
export const DetectionID = IDL.Nat;
export const DetectionRecord = IDL.Record({
  'id' : DetectionID,
  'plantType' : IDL.Text,
  'diseaseName' : IDL.Text,
  'timestamp' : IDL.Int,
  'modelUsed' : IDL.Text,
  'severity' : IDL.Text,
  'confidence' : IDL.Float64,
});
export const ModelMetrics = IDL.Record({
  'validationAccuracy' : IDL.Float64,
  'inferenceTimeMs' : IDL.Float64,
  'loss' : IDL.Float64,
  'parameters' : IDL.Nat,
  'modelName' : IDL.Text,
  'validationLoss' : IDL.Float64,
  'accuracy' : IDL.Float64,
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'getAllDiseases' : IDL.Func([], [IDL.Vec(DiseaseInfo)], ['query']),
  'getDetectionHistory' : IDL.Func([], [IDL.Vec(DetectionRecord)], ['query']),
  'getDiseaseInfo' : IDL.Func([IDL.Text], [DiseaseInfo], ['query']),
  'getModelMetrics' : IDL.Func([], [IDL.Vec(ModelMetrics)], ['query']),
  'saveDetection' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [DetectionID],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DiseaseInfo = IDL.Record({
    'id' : IDL.Nat,
    'plantType' : IDL.Text,
    'treatment' : IDL.Text,
    'diseaseName' : IDL.Text,
    'symptoms' : IDL.Text,
    'severity' : IDL.Text,
    'prevention' : IDL.Text,
  });
  const DetectionID = IDL.Nat;
  const DetectionRecord = IDL.Record({
    'id' : DetectionID,
    'plantType' : IDL.Text,
    'diseaseName' : IDL.Text,
    'timestamp' : IDL.Int,
    'modelUsed' : IDL.Text,
    'severity' : IDL.Text,
    'confidence' : IDL.Float64,
  });
  const ModelMetrics = IDL.Record({
    'validationAccuracy' : IDL.Float64,
    'inferenceTimeMs' : IDL.Float64,
    'loss' : IDL.Float64,
    'parameters' : IDL.Nat,
    'modelName' : IDL.Text,
    'validationLoss' : IDL.Float64,
    'accuracy' : IDL.Float64,
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'getAllDiseases' : IDL.Func([], [IDL.Vec(DiseaseInfo)], ['query']),
    'getDetectionHistory' : IDL.Func([], [IDL.Vec(DetectionRecord)], ['query']),
    'getDiseaseInfo' : IDL.Func([IDL.Text], [DiseaseInfo], ['query']),
    'getModelMetrics' : IDL.Func([], [IDL.Vec(ModelMetrics)], ['query']),
    'saveDetection' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [DetectionID],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };