/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DetectionID = bigint;
export interface DetectionRecord {
  'id' : DetectionID,
  'plantType' : string,
  'diseaseName' : string,
  'timestamp' : bigint,
  'modelUsed' : string,
  'severity' : string,
  'confidence' : number,
}
export interface DiseaseInfo {
  'id' : bigint,
  'plantType' : string,
  'treatment' : string,
  'diseaseName' : string,
  'symptoms' : string,
  'severity' : string,
  'prevention' : string,
}
export interface ModelMetrics {
  'validationAccuracy' : number,
  'inferenceTimeMs' : number,
  'loss' : number,
  'parameters' : bigint,
  'modelName' : string,
  'validationLoss' : number,
  'accuracy' : number,
}
export interface _SERVICE {
  'clearHistory' : ActorMethod<[], undefined>,
  'getAllDiseases' : ActorMethod<[], Array<DiseaseInfo>>,
  'getDetectionHistory' : ActorMethod<[], Array<DetectionRecord>>,
  'getDiseaseInfo' : ActorMethod<[string], DiseaseInfo>,
  'getModelMetrics' : ActorMethod<[], Array<ModelMetrics>>,
  'saveDetection' : ActorMethod<
    [string, string, number, string, string],
    DetectionID
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];